### ISSUE TITLE
Update to Mugen Souls Z

### ISSUE THREAD

**Issue by Delutto** [u3shit/neptools#10]
Hi.
You can update your tools to support Mugen Souls Z game, the file structure have just some little differences:
`struct HeaderFooter`
`{`
   `       char magic[4]; // GBNB (B=Big Endian)`
`       uint16_t field_04; // always 1`
`       uint16_t field_06; // always 0`
`       uint32_t field_08; // always 16`
`       uint32_t field_0c; // always 4`
`       uint32_t flags;`
`       uint32_t struct_offset;`
`       uint32_t struct_count;`
`       uint32_t struct_size;`
`       uint32_t types_count;`
`      uint32_t types_offset;`
`      uint32_t Entries_Count; // Text Count`
`      uint32_t string_offset;`
`      uint32_t field_30; // 0 or 4`
`      uint32_t padding[3]; // always 0`
`};`
`sizeof(HeaderFooter) == 0x40`

**Comment by u3shit** [comment]
Hmm, it looks like it's big endian, then it's related to #6, partially fixed it a70677d but I don't like that solution too much. Do you have some sample files?

**Comment by Delutto** [comment]
Here: [https://www56.zippyshare.com/v/IkMIekZ8/file.html](url)

**Comment by u3shit** [comment]
I've updated the ljx branch. I think I'll merge the cl3 changes from master, and then deprecate the whole old master and make ljx the new master, that's the way forward.
