### ISSUE TITLE
Megadimension Neptunia VII : Translation of Dialogues

### ISSUE THREAD

**Issue by Dowar** [u3shit/neptools#11]
Hello, I'm trying to translate megadimension into French but I find myself facing a big problem with the translation of the dialogues, the main.cl3 contain a main.DAT that is not supported by Neptool (I try to change the extension by curiosity in .gstr so that stcm-editor the extract and to my great surprise it worked perfectly but as I thought the game can not read the main.cl3 recompiled since the extension inside is not .DAT and change it change in main.DAT.txt obviously does not work either since the neptool server does not know this format)

is it possible to work around the problem?
thank you in advance ;)

**Comment by u3shit** [comment]
It should work certainly work with main.cl3 files from VII. What version do you use? Just open the main.cl3 file with it and it should produce a main.cl3.txt.

**Comment by Dowar** [comment]
i'm use the 0.3.7 version, I try to modify the texts of the file in "Megadimension Neptunia VII\CONTENTS\GAME00000\event\script" but the cl3-tool turns main.cl3 into main.cl3.out that contain a main.DAT

**Comment by Dowar** [comment]
After a few more tests I finally succeeded by renaming the main.DAT in main.gstr, then decompile and rename in main.cl3.txt, thanks a lot ;)

**Comment by u3shit** [comment]
Just use stcm-editor on the main.cl3. cl3-tool is to extract contents of the cl3 if you want to edit textures/etc embedded into it.

**Comment by Dowar** [comment]
ow, sorry it's perfect suddenly, thank you very much for the tools anyway :)
