### ISSUE TITLE
Problem with cl3 dragging in stcm-editor.

### ISSUE THREAD

**Issue by rkad72** [u3shit/neptools#12]
I wanted to create a new NeptuniaVII character texture cl3 instead, so I dragged it to stcm-editor. However, dragging did not even work. So, I tried to execute the command directly through cmd, but this time cl3 file access was denied or error message was displayed. I do not really know what the problem is. Please let me know how to fix it.

**Comment by u3shit** [comment]
You'll have to rename stcm-editor to cl3-tool to use file dragging.
About cmd: could you please post the exact command you tried to run and any output of the program?

**Comment by rkad72** [comment]
It's good to do what you told me. Thank you!  It is a cl3 file created by using the strtool once.
