### ISSUE TITLE
.ffu font file and convert to Unicode

### ISSUE THREAD

**Issue by B1Ancc** [u3shit/neptools#13]
Morning, 
I wanna ask if this tool could modify the .ffu file and change the font inside it.
But if it couldn't, can you please guide me how to modify the .ffu to change the font and convert it to Unicode? Since the original .ffu can't handle some Special Character like "ô", it becomes " ﾃｲ".
Btw the instructions in the #1 isn't clear enough to figured out how to edit the .ffu file...
Thank you very much for notice this!

**Comment by u3shit** [comment]
Hi,
Unfortunately Neptools doesn't support .ffu files yet. Older engines (before Neptunia V-II) used shift-jis internally, so you have to save the texts as shift-jis (which of course lacks many accented characters).

**Comment by fuzzfactory0** [comment]
@B1Ancc Can you please explain how you modified the .ffu file?
