### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by Lmmb74** [u3shit/neptools#15]
Hello. After compilation, I'm left with the stcm-editor file but I'm unable to find the executable. Sorry if I'm the one at fault, since it's my first time using waf. I'm using g++-7 and boost-1.73.

**Comment by u3shit** [comment]
Hello,
The executable should be at `build/stcm-editor` on Linux.

**Comment by Lmmb74** [comment]
If it is a folder, then it's not generated. Also, the stcm-editor file doesn't contain the executable.

**Comment by u3shit** [comment]
No, `build` is a folder, and `stcm-editor` file inside should be the executable. What does `file build/stcm-editor` output?

**Comment by Lmmb74** [comment]
stcm-editor: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=58e8ec4f6e034a4042120a483a4082a611da9d8f, for GNU/Linux 3.2.0, with debug_info, not stripped

**Comment by u3shit** [comment]
Yes, that is an executable.

**Comment by Lmmb74** [comment]
Then I don't know how to implement it to the game.

**Comment by u3shit** [comment]
I don't know what you want to implement. There are some examples in the README on how to use stcm-editor. If you're looking for the server that hooks into the game, that's only available when compiling for 32-bit windows.

**Comment by Lmmb74** [comment]
Ok, I didn't read that xD

**Comment by Lmmb74** [comment]
Sorry for the inconveniences and thanks for your help.
