### ISSUE TITLE
Have problem with .cl3. Again.

### ISSUE THREAD

**Issue by Hocorog** [u3shit/neptools#17]
Hello.
I have a problem with the .CL3 files again. The program unpacks everything perfectly, but in some events of Death and re;Quest there is an event in which it is necessary to make a choice.
![image](https://user-images.githubusercontent.com/76913809/105486812-f1865e00-5cd0-11eb-865a-6b60f5ca172a.png)

The choice are located in the same CL3 file as the event itself. The text is unpacked, but the selection itself is not.
![image](https://user-images.githubusercontent.com/76913809/105486836-fc40f300-5cd0-11eb-94d7-2032d7b5564b.png)

Using Notepad++, I tried to translate the choice, but the game did not display the changed text.
![image](https://user-images.githubusercontent.com/76913809/105486859-03680100-5cd1-11eb-8c4b-71cd476c7cb8.png)

Is there any way to get this text out of there? If there is, can you help? And is there anything I can do here?

**Comment by u3shit** [comment]
You didn't provide a cl3, but if you feel adventurous you might try the lua export, that's a bit more scary, but it contains more editable information. Try `stcm-editor -m auto-lua`.

**Comment by Hocorog** [comment]
Everything works perfectly! Thank you very much for your decision.

**Comment by Hocorog** [comment]
Hi! Through auto-lua, I was trying to translate the Quiz Millionep in Megadimension Neptunia VIIR, and there was a problem. Some answer options cannot be translated. The .lua file does not contain it. Using the HEX editor, I found them, but stcm-editor didn't unpack them for some reason. Is there any way to fix this?
UPD: I tried to translate in the HEX editor, and it kind of worked, but I'm not sure if the game will work properly.

It seems to me that in the highlighted part there should be a answer options that cannot be translated.
![image](https://user-images.githubusercontent.com/76913809/117541315-ef72b180-afd8-11eb-97c6-81949cd26ce9.png)

In the HEX editor, I found the answer option
![image](https://user-images.githubusercontent.com/76913809/117541405-5728fc80-afd9-11eb-9b90-1384d31f8b7b.png)

In the game it looks something like this:
![20210508182131_1](https://user-images.githubusercontent.com/76913809/117541606-42009d80-afda-11eb-9016-5af95fecacb8.jpg)

Original files and .lua-files:
[QUIZ.zip](https://github.com/u3shit/neptools/files/6445965/QUIZ.zip)

**Comment by u3shit** [comment]
Um, there's some heuristic there and it parses a 4 byte long data as an int32 instead of a string (6579538 is 0x646552)... Could you try and replace that `data(0, 1, 1):build(function() int32(6579538) end)` with `string_data("whatever")`?

**Comment by Hocorog** [comment]
Yes, it worked, I'm even a little surprised.=)
But can such changes cause any crashes of the game?
Thanks for the answer.
![image](https://user-images.githubusercontent.com/76913809/117646381-4e5b3680-b151-11eb-8d3a-e807f3506e95.png)

**Comment by u3shit** [comment]
The problem is that int32s and strings of length <= 3 are stored in the same way, and neptools can't determine which is the correct. If you replace an integer with a string where the game expects an integer, that can certainly crash the game, but here it expects a string so it should be okay. Probably.

**Comment by Hocorog** [comment]
OK, got it. Then I close the question. Thank you again for advice.
