### ISSUE TITLE
Omega Quintet Support

### ISSUE THREAD

**Issue by marcussacana** [u3shit/neptools#19]
The lastest release, v0.3.7 can't dump any text from the Omega Quintet cl3 files...

When I try I get random errors such:
```
ERROR[stcm-editor]: Fatal error, aborting
ERROR[stcm-editor]: Stcm::InstructionItem::Parameter: invalid data
ERROR[stcm-editor]:
ERROR[stcm-editor]: Details: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
ERROR[stcm-editor]: Dynamic exception type: struct Neptools::DecodeError
ERROR[stcm-editor]: std::exception::what: Stcm::InstructionItem::Parameter: invalid data
ERROR[stcm-editor]: [struct Neptools::FailedExpressionTag *] = !"Unknown special"
ERROR[stcm-editor]: [struct Neptools::ProcessedOptionTag *] = --export-txt
ERROR[stcm-editor]: [Source] = bin("E:/Program Files (x86)/Steam/steamapps/common/Omega Quintet/System/global/Script/RPG/SControl/main.cl3", 0x1560, 0x1e30), pos: 28
```
Sample: [database.zip](https://github.com/u3shit/neptools/files/5965023/database.zip)

**Comment by u3shit** [comment]
The sample you gave me doesn't contain any stcm, it's just a cl3 with some gbin inside. Anyway, try with a newer version first, for example from here: https://jenkins.neptards.moe/job/neptools_build_test/53/compiler=clang-msvc,mode=rel/artifact/build/

**Comment by marcussacana** [comment]
I have more files with different errors, I will look again later

**Comment by marcussacana** [comment]
Yeah, looks like all .cl3 files don't have text, only .gbin and .gstr is used in this game, thx for the dev build by the way.
