### ISSUE TITLE
stcm-editor has stopped working

### ISSUE THREAD

**Issue by OronDF343** [u3shit/neptools#2]
Trying to extract GAME00000\event\script\xxxx\main.cl3 (they can be extracted with strtool) in Re;Birth1, It creates a 0kb txt file and crashes.
![stcm-editor-crash](https://cloud.githubusercontent.com/assets/5132940/16455638/ba3675ce-3e1d-11e6-88d6-25d2ac0aa006.PNG)

**Comment by u3shit** [comment]
Thanks, hopefully fixed in v0.3.4.

I should make more unit tests...
