### ISSUE TITLE
STCM Editor Corrupting gbin

### ISSUE THREAD

**Issue by marcussacana** [u3shit/neptools#21]
I'm trying import back the text to a .gbin str, and for some reason the genareted file only contains few lines instead the all text, the input file for example is 15kb, the output 6kb
[Sample.7z.zip](https://github.com/u3shit/neptools/files/6367274/Sample.7z.zip)

Original File:
![image](https://user-images.githubusercontent.com/10576957/115912353-984fd700-a445-11eb-841b-858f3b691334.png)

Result File:
![image](https://user-images.githubusercontent.com/10576957/115912311-8837f780-a445-11eb-8277-7260d854b70c.png)

**Comment by u3shit** [comment]
```
―――――――――――――――――――――――――――――――――――――――― 10000
Io
―――――――――――――――――――――――――――――――――――――――― 10001
Estou tão preocupada.
―――――――――――――――――――――――――――――――――――――――― 10001
Io
―――――――――――――――――――――――――――――――――――――――― 10002
```
Oh shit, multiple lines have the same id. This will require some format changes. What game is this even?

**Comment by u3shit** [comment]
Since it looks like you already use some random parameters, I've added a new parameter, --simple-ids. This will change how the ids are calculated, so multiple lines won't end up with conflicting ids. However you'll have to manually fix up old txt files (I hope you don't have too much of them)

**Comment by marcussacana** [comment]
It's from Moero Chronicles

**Comment by marcussacana** [comment]
> However you'll have to manually fix up old txt files (I hope you don't have too much of them)

Isn't a problem, Thank you.
the test build don't finished yet, but I supose you already tested and is fixed, then i will close the issue, thank you :)
