### ISSUE TITLE
Translation possible ?

### ISSUE THREAD

**Issue by anthonymiegge** [u3shit/neptools#23]
Hi !
Just discovered your tool and it's not clear enough for me what I could do with it .
Could I translate the game from it ? Could I create a patch to apply my translation on any user's game ? And could I link it to Dropbox in order to work as a team ?
I want to be sure about what I could to with this tool, before downloading it, because it's my first time downloading something from GitHub ^^'

Thanks in advance for your answer.

**Comment by u3shit** [comment]
It was originally made for Neptunia Re;Birth 1-3, but it works for some other Compile Heart/Idea Factory games that use similar engines (sometimes you need to use other tools, if you want to mod a game you'll have to tinker a bit). For anything else, probably not.
Neptools outputs plain text files, dropbox should have no problem with them (or any other file synchronization tool).

**Comment by anthonymiegge** [comment]
> It was originally made for Neptunia Re;Birth 1-3, but it works for some other Compile Heart/Idea Factory games that use similar engines (sometimes you need to use other tools, if you want to mod a game you'll have to tinker a bit). For anything else, probably not.
> Neptools outputs plain text files, dropbox should have no problem with them (or any other file synchronization tool).

Thanks for your answer.
One last question before closing this : How can I export my modifications on other computers ? Like, if I want them to use my future translation, what do I need them to download ?

**Comment by u3shit** [comment]
If the neptools server works with your game, you can just distribute the txt files and the server (take a look at how Re;Translation work for Neptunia Re;Birth 2 and 3), otherwise you'll likely have to distribute the modified files, or come up with a custom solution.

**Comment by anthonymiegge** [comment]
Right, thanks for your help, it really helped me !
Have a nice day on the web !
