### ISSUE TITLE
NepVII , some"main.cl3"File contains multiple text

### ISSUE THREAD

**Issue by were404** [u3shit/neptools#3]
Some "GAME00000/event/script/xxxxx/main.cl3" file contains two or more text, but the stcm-editor only extract the first paragraph, 
such as main.cl3#21030 and #22140 
[script.zip](https://github.com/u3shit/neptools/files/467196/script.zip)

**Comment by u3shit** [comment]
Thanks, it should be fixed now. But I'll tackle another issue before making a new release.
