### ISSUE TITLE
In VII , the question and answer of [Quiz! Millionep!] can not be export

### ISSUE THREAD

**Issue by Pantaku** [u3shit/neptools#5]
The following .cl3 is [Quiz! Millionep!]  : 60040 61040 62040 63040 64040 65040
that six dat include every question&answers text , stcm can not export it .
then we try to compile it in HEX , but neptools errored...

[cl3 of [Quiz Millionep].zip](https://github.com/u3shit/neptools/files/482863/cl3.of.Quiz.Millionep.zip)

![p-screen20160920223811](https://cloud.githubusercontent.com/assets/22323599/18674986/88ec2502-7f83-11e6-9cb5-31d962c07653.png)

**Comment by u3shit** [comment]
Which version do you use? It does not error out on the attached files for me.
It doesn't export actual questions and answers, only the dialogue, it's a known problem, it'll be possible to edit them someday (probably not before finishing and merging the ljx branch)...
What do you mean by "we try to compile it in HEX" -- edit it in a hex editor? There are too many references in the file that needs updating, so you can't just do it. Replacing strings with the same length or shorter and padding with 0 bytes should work though.

**Comment by u3shit** [comment]
No response in almost 3 months. Reopen if problem still exist.
