### ISSUE TITLE
.ffu font need help

### ISSUE THREAD

**Issue by benladen** [u3shit/neptools#7]
I am working on porting Superdimension Neptune VS to Chinese, and there is a new version .ffu file, is there a tool for editing it?Thx.
.ffu file is here, https://mega.nz/#!rYFFALqY!27s57xftPzRNfgoZMBj4ebq5gY5VbILBkygIzcMm-zQ

**Comment by u3shit** [comment]
I don't know. I don't even have a PS Vita to begin with. Plus Neptools has no support for .ffu files at the moment. See #1 for some discussion.
