### ISSUE TITLE
GBIN from DLC

### ISSUE THREAD

**Issue by Mugetsuga** [u3shit/neptools#9]
Hi, 
I'm editing texts here and there in Re;Birth1, until now everything was fine, but when I wanted to edit the GBIN files from NRB1DLC000000012, the changes won't take effect. I even tried to replace in the PAC file, but doing that makes the items disappear from the game.
DLC where the edit works:
NRB1DLC000000007
NRB1DLC000000008
NRB1DLC000000009
Is it something I'm doing wrong?

**Comment by u3shit** [comment]
I didn't check the DLCs until now so I have no idea what could be wrong. Maybe the game doesn't even use that file (there's a lot of unused/leftover data in the data files...).
Could you try running (the debug version) of neptools server with something like `-f log.txt -lcpk=3` and check the log.txt if it actually does something with the aforementioned file?

**Comment by Mugetsuga** [comment]
I don't think they are leftovers. The files I'm trying to edit are stitem12.gbin and stremake12.gbin. These files contains the names and descriptions of items or dungeons that have been added for the DLC.
Here's the log:
https://www.mediafire.com/?fejji2f5l4rtb38
For the two files I mentionned above, it says:
can't fs hook
CreateFileW failed

**Comment by u3shit** [comment]
Hmm, error code 3 means path found. Does `neptools/DLC/NRB1DLC000000012/NRB1DLC000000012\database\stitem12.gbin` (or `.gbin.txt`) exists?

**Comment by Mugetsuga** [comment]
So that's what I was doing wrong. My path until now was:
neptools\DLC\NRB1DLC000000012\database\
I was missing another NRB1DLC000000012 folder, now everything is fine, thanks.
